name: EvoSwingGolf
favicon: null
layout_spectrum: 0.24412
typography_spectrum: 0.8982235239818692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f2f7fb'
    - '#009cf3'
    - '#b8a326'
    - '#73777a'
  brandStrength: 0.8125
  lightness: 0.9375
  saturation: 0.25
  rhythmicContrast: 0.29722061613574624
purpose: []
